### ISSUE TITLE
Dropdown RefinementList does not work with latest instantsearch.js 

### ISSUE THREAD

**Issue by stephanemartinw** [algolia/instantsearch#5431]
### 🐛 Current behavior

2 errors are generated. Latest version of instantsearch.js (4.49.4) seems not to support the given dropdown.js script.

dropdown.js:92 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at Object.init (dropdown.js:92:37)
    at index.ts:535:18
    at Array.forEach (<anonymous>)
    at Object.init (index.ts:526:20)
    at h.value (InstantSearch.ts:558:20)
    at isengine.js?ver=1.2.1:389:8
init @ dropdown.js:92
(anonymous) @ index.ts:535
init @ index.ts:526
value @ InstantSearch.ts:558
(anonymous) @ isengine.js?ver=1.2.1:389

After a first search query : 

RefinementList.tsx:322 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'templates')
    at a.value (RefinementList.tsx:322:57)
    at Tr (preact.module.js:1:5819)
    at wr (preact.module.js:1:2149)
    at Tr (preact.module.js:1:6150)
    at L (preact.module.js:1:8302)
    at ti.attribute (refinement-list.tsx:262:5)
    at Object.render (connectRefinementList.ts:348:11)
    at Object.render (panel.tsx:336:25)
    at index.ts:603:18
    
    

### 🔍 Steps to reproduce

When following these steps from Algolia documentation: 
https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/facet-dropdown/js/#overview

### Live reproduction

https://codesandbox.io/s/keen-lake-pp46dw

### 💭 Expected behavior

Same as described in the Algolia documentation: a dropdown displaying facet values.

### Package version

instantsearch.js 4.49.4, algoliasearch 4.14.3

### Operating system

macOS

### Browser

Chrome 108

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mustanguy69** [comment]
Hello,
We had the same issue !
Rolling back to version 4.7.0 fix our issue

Sort & filters were not working in 4.7.3

**Comment by stephanemartinw** [comment]
Please see https://github.com/algolia/doc-code-samples/issues/422 for more information.
