### ISSUE TITLE
Fix storybook examples

### ISSUE THREAD

**Issue by gaetansenn** [algolia/instantsearch#6368]
### 🐛 Current behavior

This current ais-pagination example fail to open https://instantsearchjs.netlify.app/stories/vue/?path=/story/ais-pagination--

The error
```
algoliasearch_lite__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function
TypeError: algoliasearch_lite__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function
    at previewWrapper (https://instantsearchjs.netlify.app/stories/vue/main.48e6b0d8faa6bd9cd3d9.bundle.js:2:354932)
    at Module.<anonymous> (https://instantsearchjs.netlify.app/stories/vue/main.48e6b0d8faa6bd9cd3d9.bundle.js:2:562829)
    at 942 (https://instantsearchjs.netlify.app/stories/vue/main.48e6b0d8faa6bd9cd3d9.bundle.js:2:566183)
    at __webpack_require__ (https://instantsearchjs.netlify.app/stories/vue/runtime~main.48e6b0d8faa6bd9cd3d9.bundle.js:1:1301)
    at webpackContext (https://instantsearchjs.netlify.app/stories/vue/main.48e6b0d8faa6bd9cd3d9.bundle.js:2:561759)
    at https://instantsearchjs.netlify.app/stories/vue/main.48e6b0d8faa6bd9cd3d9.bundle.js:2:499063
    at Array.forEach (<anonymous>)
    at loadStories (https://instantsearchjs.netlify.app/stories/vue/main.48e6b0d8faa6bd9cd3d9.bundle.js:2:499028)
    at https://instantsearchjs.netlify.app/stories/vue/vendors~main.48e6b0d8faa6bd9cd3d9.bundle.js:2:1727128
    at render (https://instantsearchjs.netlify.app/stories/vue/vendors~main.48e6b0d8faa6bd9cd3d9.bundle.js:2:1706722)
    ```

### 🔍 Steps to reproduce

Link:  https://instantsearchjs.netlify.app/stories/vue/?path=/story/ais-pagination--

### Live reproduction

https://instantsearchjs.netlify.app/stories/vue/?path=/story/ais-pagination--*

### 💭 Expected behavior

The example works 

### Package version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
Not sure what caused it (probably webpack/babel config since moving to v5 of algoliasearch). The js examples still seem to work, so you can use those instead for now: https://instantsearchjs.netlify.app/stories/js/?path=/story/pagination-pagination--default

We were thinking of possibly removing the storybooks as they don't bring much value and are decent amount of work. What are you using the storybooks for. Just to see an example of what the widget renders like or something else as well?

**Comment by gaetansenn** [comment]
Hi @Haroenv thank you for your reply. 

Agree with you for the usage of storybook

**Comment by gaetansenn** [comment]
I dont really know how to report a bug in your documentation but the liteClient is imported like this :

`import { liteClient } from 'algoliasearch/lite'`

and not 

`import { liteClient } from 'algoliasearch'`

https://www.algolia.com/doc/libraries/javascript/v5/methods/search/

**Comment by Haroenv** [comment]
The first way is the correct way @gaetansenn, if you import from "non-lite" it's `import { algoliasearch } from 'algoliasearch'`

**Comment by gaetansenn** [comment]
Yes i know just point out the error from the doc:

![Screenshot 2024-09-24 at 13 59 49](https://github.com/user-attachments/assets/a3fbc0bc-b425-4eb2-929f-68d1633373f0)

**Comment by Haroenv** [comment]
Ah I see I misread your comment, fixing :)

**Comment by Haroenv** [comment]
fixed in https://github.com/algolia/instantsearch/pull/6483
